# Generated by Django 3.2.7 on 2021-10-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0004_alter_quest_data_serial_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest_data',
            name='id_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
