# Generated by Django 3.2.7 on 2021-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0007_rename_id_course_result_test_id_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluation_stdn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quote', models.CharField(max_length=100)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('id_students', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='evaluation_tch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cat_1', models.IntegerField()),
                ('cat_2', models.IntegerField()),
                ('cat_3', models.IntegerField()),
                ('cat_4', models.IntegerField()),
                ('cat_5', models.IntegerField()),
                ('cat_6', models.IntegerField()),
                ('cat_7', models.IntegerField()),
                ('cat_8', models.IntegerField()),
                ('cat_9', models.IntegerField()),
                ('cat_10', models.IntegerField()),
                ('cat_11', models.IntegerField()),
                ('cat_spec', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(max_length=15)),
                ('id_teacher', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='result_test',
            name='survey',
            field=models.CharField(default='non', max_length=10),
            preserve_default=False,
        ),
    ]
