# Generated by Django 3.2.7 on 2021-09-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_second',
            name='profile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
