# Generated by Django 3.2.7 on 2021-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_second',
            name='no_induk',
            field=models.CharField(max_length=20),
        ),
    ]
