# Generated by Django 3.2.7 on 2021-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0002_user_second_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_user',
            old_name='guru_id',
            new_name='id_class',
        ),
    ]
