# Generated by Django 3.2.7 on 2021-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0003_rename_guru_id_students_user_id_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_user',
            name='guru_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students_user',
            name='id_class',
            field=models.IntegerField(blank=True),
        ),
    ]
