# Generated by Django 3.2.7 on 2021-10-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0004_auto_20211007_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_user',
            name='id_class',
        ),
    ]
