# Generated by Django 3.2.7 on 2021-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0005_remove_students_user_id_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_user',
            name='id_class',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
