# Generated by Django 3.2.7 on 2021-10-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0006_students_user_id_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_user',
            name='guru_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='students_user',
            name='id_class',
            field=models.IntegerField(null=True),
        ),
    ]
