# Generated by Django 3.2.7 on 2021-10-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0007_auto_20211007_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theachers_user',
            name='admin_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
