# Generated by Django 3.2.7 on 2021-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSys', '0008_alter_theachers_user_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_user',
            name='id_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
